version: '3.1'

services:
  database_pg:
    image: postgres
    # container_name: database_pg
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: spring-boot_base-app
    ports:
    - 5432:5432
    volumes:
    - ./pg-data:/var/lib/postgresql/

  server_maven:
    image: maven
    # container_name: server_maven
    environment:
      DB_URL: jdbc:postgresql://database_pg:5432/spring-boot_base-app
      # DB_URL: jdbc:postgresql://host.docker.internal:5432/spring-boot_base-app
    ports:
    - 80:80
    links:
      - database_pg
    volumes:
    - ./:/usr/src/
    working_dir: /usr/src/
    command: bash -c "mvn spring-boot:run"
    # command: bash -c "mvn clean install spring-boot:run"