server:
  port: 80

  error:
    include-stacktrace: on-param

spring:
  thymeleaf:
    mode: HTML
    cache: FALSE

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://host.docker.internal:5432/spring_base_app
